spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #config-location: classpath:mybatis-config.xml
  type-aliases-package: tk.mybatis.springboot.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count = countSql
judger:
  path: http://127.0.0.1:8080
